language: node_js
  node_js:
    - "node"
deploy:
  provider: heroku
  api_key:
    secure: g+V+L+X2Ht+KlELITMKV6CmfzfTuOvH0TCo1b2wSL0sxnIAu2E5nTAZ74NC3qwgjY7bSQx0JOccf9Tz61v0tR7XSRIBjgVh6qPBHqSm7ZICYFsOulfHbVzf7AJ4tN72k6Es+tj3VBc2nbhfDy2OKWImdMVJUwsa22UGknyge14/D65WNG1t0yrbazcvaM96eOdawR53fKv+/FoduwAg/oDSKgQQXm+bZsB/7okEOwwoQVWozQHhd0s4jIvAlEREq9bqI3i2OqOS71cF/QWUSOl/dFXV/12zWX5tzjbwSE+6fCUlNxRlqnDTAra6NQf/UOaO+jHUomhKP7YO30Bvbroso0IFLLo5kd22mLfxzOybbSGzR1B6qZ5ql1Vz3FGLPgf0YN51U+GfEAXLf32qtHVZnCZurPz8HYbcWSF4Lj1N/OpUAzug96FhcbLejFEyCbOCB242kc5iic4T5OapS0sroC3ejG5LzrP2cZdh5qDv5nUjXnpNAa94SSTH2Cj6S8X6MnasyyYbiqMLaaxH23CI/wkzaNpBdLdlCOr2ry8LksVe2cDPyy7UpJB0BHwdM+ngtR6MbYbD0+QPhu6JwN2B+PJib26syRWDjpJMRxGDdsc/7PV1sGktnCby0YKPJyvGMwhARkkYCN9WJ46p+0svke6ybXcJxsoL8Qhi1OjU=
  app: limitless-ridge-16599